# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-14 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0002_auto_20170501_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('categorie_depenses', models.CharField(blank=True, max_length=255)),
                ('nom_de_la_depense', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Categoriebudget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
        migrations.AddField(
            model_name='budget',
            name='categoriebudget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='budget.Categoriebudget'),
        ),
    ]
