# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-14 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='categorie_depenses',
            field=models.CharField(max_length=255),
        ),
    ]
