# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-14 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20170514_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='categorie_depenses',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2),
        ),
    ]
