# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-14 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0004_auto_20170514_1152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='categorie_depenses',
            new_name='catégorie_dépenses',
        ),
        migrations.RenameField(
            model_name='budget',
            old_name='nom_de_la_depense',
            new_name='nom_de_la_dépense',
        ),
        migrations.AddField(
            model_name='budget',
            name='montant_de_la_dépense',
            field=models.DecimalField(decimal_places=10, default=1, max_digits=19),
            preserve_default=False,
        ),
    ]
