# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-14 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0006_auto_20170514_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='catégorie_dépenses',
            field=models.CharField(choices=[('TRANSPORT', 'Transport'), ('HEBERGEMENTS', 'Hébergements'), ('RESTAURATION', 'Restauration'), ('VISITES', 'Visites'), ('AUTRES', 'Autres')], max_length=255),
        ),
    ]
