# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-15 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_auto_20170514_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='catégorie_dépenses',
            field=models.CharField(choices=[('TRANSPORT', 'Transport'), ('HÉBERGEMENTS', 'Hébergements'), ('RESTAURATION', 'Restauration'), ('VISITES', 'Visites'), ('SANTÉ', 'Santé'), ('AUTRES', 'Autres')], max_length=255),
        ),
    ]
