# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-01 10:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorie', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('content', models.TextField()),
                ('image', models.ImageField(upload_to=posts.models.upload_location)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('publier', models.BooleanField()),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorie.Categorie')),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorie.SubCategorie')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
