# Generated by Django 2.2.7 on 2019-12-01 11:14

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorie', '0003_auto_20191201_1214'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Commentairee', 'verbose_name_plural': 'Commentaires'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Billet', 'verbose_name_plural': 'Billets'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='pays',
        ),
        migrations.AddField(
            model_name='post',
            name='sous_categorie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='categorie.SubCategorie', verbose_name='Sous-Catégorie de rattachement'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='categorie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorie.Categorie', verbose_name='Catégorie de rattachement'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
    ]
