# Generated by Django 2.2.7 on 2019-12-02 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191201_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Adresse Email'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='message',
            field=models.TextField(verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='nom',
            field=models.CharField(max_length=100, verbose_name='Pseudo'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post_rattachement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post', verbose_name='Billet de rattachement'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='valide',
            field=models.BooleanField(default=True, verbose_name='Autorisé'),
        ),
    ]
