# Generated by Django 2.1.2 on 2019-08-09 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='post_rattachement',
        ),
    ]
