# Generated by Django 2.1.2 on 2019-08-09 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_comments_post_rattachement'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='post_rattachement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
            preserve_default=False,
        ),
    ]
