# Generated by Django 2.1.2 on 2019-08-09 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20190809_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='post_rattachement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
