# Generated by Django 2.2.7 on 2019-11-25 14:51

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoriemap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('adresse_complète', models.CharField(blank=True, max_length=255)),
                ('commentaire_adresse', models.CharField(blank=True, max_length=255)),
                ('etape', models.IntegerField()),
                ('position', geoposition.fields.GeopositionField(max_length=42)),
                ('categoriemap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='map.Categoriemap')),
            ],
        ),
    ]
