# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-07 10:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PointOfInterest',
            new_name='Map',
        ),
    ]
