# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-07 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20170507_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='name',
            new_name='nom',
        ),
    ]
