# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-07 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170501_1834'),
        ('map', '0003_auto_20170507_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoriemap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
        migrations.AddField(
            model_name='map',
            name='categoriemap',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.Categoriemap'),
            preserve_default=False,
        ),
    ]
