# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-08 11:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_auto_20170507_1337'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='etape',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
