# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-13 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_map_etape'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='adresse',
            field=models.TextField(blank=True),
        ),
    ]
