# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-13 09:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_auto_20170513_1146'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='adresse',
            new_name='adresse_complète',
        ),
    ]
