# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-13 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_auto_20170513_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='commentaire_adresse',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
