# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-01 10:18
from __future__ import unicode_literals

import categorie.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_categorie', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['nom_categorie'],
            },
        ),
        migrations.CreateModel(
            name='SubCategorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_subcategorie', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(upload_to=categorie.models.upload_location)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categorie.Categorie')),
            ],
            options={
                'ordering': ['nom_subcategorie'],
            },
        ),
    ]
