# Generated by Django 2.2.7 on 2019-12-02 14:07

from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorieport',
            options={'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Portfolio', 'verbose_name_plural': 'Portfolios'},
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='categorieportfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Categorieport', verbose_name='Catégorie de rattachement portfolio'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(upload_to=portfolio.models.upload_location, verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titre'),
        ),
    ]
